/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A11yBanner: typeof import('./src/components/a11y/A11yBanner.vue')['default']
    A11yLiveRegion: typeof import('./src/components/a11y/A11yLiveRegion.vue')['default']
    A11yToolbar: typeof import('./src/components/a11y/A11yToolbar.vue')['default']
    AdminLogin: typeof import('./src/components/auth/AdminLogin.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HearingProfileForm: typeof import('./src/components/reco/HearingProfileForm.vue')['default']
    HomeGuideCard: typeof import('./src/components/home/HomeGuideCard.vue')['default']
    HomeHeroCarousel: typeof import('./src/components/home/HomeHeroCarousel.vue')['default']
    HomeLiveStats: typeof import('./src/components/home/HomeLiveStats.vue')['default']
    HomeSidebar: typeof import('./src/components/home/HomeSidebar.vue')['default']
    HomeTrustTiles: typeof import('./src/components/home/HomeTrustTiles.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesBarChart: typeof import('./src/components/admin/SalesBarChart.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SpeechCaptionOverlay: typeof import('./src/components/a11y/SpeechCaptionOverlay.vue')['default']
    ToastHost: typeof import('./src/components/ToastHost.vue')['default']
    UserLogin: typeof import('./src/components/auth/UserLogin.vue')['default']
    UserRegister: typeof import('./src/components/auth/UserRegister.vue')['default']
  }
}
