/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A11yBanner: typeof import('./src/components/a11y/A11yBanner.vue')['default']
    A11yLiveRegion: typeof import('./src/components/a11y/A11yLiveRegion.vue')['default']
    A11yToolbar: typeof import('./src/components/a11y/A11yToolbar.vue')['default']
    AdminLogin: typeof import('./src/components/auth/AdminLogin.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FlameGradientIcon: typeof import('./src/components/icons/FlameGradientIcon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HearingProfileForm: typeof import('./src/components/reco/HearingProfileForm.vue')['default']
    HomeGuideCard: typeof import('./src/components/home/HomeGuideCard.vue')['default']
    HomeHeroCarousel: typeof import('./src/components/home/HomeHeroCarousel.vue')['default']
    HomeLiveStats: typeof import('./src/components/home/HomeLiveStats.vue')['default']
    HomeSidebar: typeof import('./src/components/home/HomeSidebar.vue')['default']
    HomeTrustTiles: typeof import('./src/components/home/HomeTrustTiles.vue')['default']
    PageTransitionOverlay: typeof import('./src/components/PageTransitionOverlay.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    ParticleCanvas: typeof import('./src/components/cover/ParticleCanvas.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesBarChart: typeof import('./src/components/admin/SalesBarChart.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SpeechCaptionOverlay: typeof import('./src/components/a11y/SpeechCaptionOverlay.vue')['default']
    ToastHost: typeof import('./src/components/ToastHost.vue')['default']
    UserLogin: typeof import('./src/components/auth/UserLogin.vue')['default']
    UserRegister: typeof import('./src/components/auth/UserRegister.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
